### ISSUE TITLE
Methods using async_contextmanager decorator don't pass pylint

### ISSUE THREAD

**Issue by zbuc** [agronholm/asyncio_extras#1]
I have a context manager method using the `async_contextmanager` decorator:

```
@asyncio_extras.async_contextmanager
async def scoped_session():
    session = Session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()
```

And then I use this context manager like so:

```
async def create_api_key(module):
    async with scoped_session() as session:
        pass
    pass
```

When I try to run this through `pylint`, it fails, being unable to find the context manager object's `__aenter__` and `__aexit__` methods.

```
$ pylint -E file.py
No config file found, using default configuration
************* Module file
E:  6,10: Async context manager 'generator' doesn't implement __aenter__ and __aexit__. (not-async-context-manager)
```

**Comment by agronholm** [comment]
What do you expect me to do about it?

**Comment by zbuc** [comment]
Whatever you want. I was just letting you know.

**Comment by agronholm** [comment]
Where does this `generator` come from that the error refers to?

**Comment by zbuc** [comment]
It's referring to the `session` object created here:

`    async with scoped_session() as session:`

I rewrote the code to not use `asyncio-extras` like this:

```
class ScopedSession():
    def __init__(self):
        self.session = None

    async def __aenter__(self):
        self.session = Session()
        return self.session
    
    async def __aexit__(self, exc_type, exc, tb):
        try:
            self.session.commit()
        except:
            self.session.rollback()
            raise
        finally:
            self.session.close()
            self.session = None
```

and it works fine, but I wanted to report this in case you wanted to try fixing the library.

**Comment by agronholm** [comment]
What's there to fix? Isn't this a bug in pylint rather than asyncio_extras?

**Comment by s0undt3ch** [comment]
This is also 3.6 syntax, ie, yield in an async def...

**Comment by agronholm** [comment]
Does pylint not handle 3.6 syntax?

**Comment by s0undt3ch** [comment]
Oh, sorry, it does, my comment was kind of unrelated to the issue(which i found on a google search for a 3.5 solution to the syntax issue). And afterwards I noticed that you can still use this with 3.5 with async_generator... However, not when the code is cython compiled(which is also not related to this issue).

**Comment by agronholm** [comment]
If this is still a problem, you should probably file a bug against pylint since everything is working correctly on this end.
