### ISSUE TITLE
Is it ok to use lambda instead partial in call_async?

### ISSUE THREAD

**Issue by kiddten** [agronholm/asyncio_extras#3]
call_async
https://github.com/agronholm/asyncio_extras/blob/master/asyncio_extras/threads.py#L143

**Comment by agronholm** [comment]
Why wouldn't it be?

**Comment by kiddten** [comment]
Indeed. Probably just misunderstood func doctring with mention partial. Though it is some kind of restriction :)

**Comment by agronholm** [comment]
Using `partial` or `lambda` is only necessary if you need to pass a keyword argument named `loop` to the target callable.
